export const FETCH_USER_INSIGHT_GENRES = 'FETCH_USER_INSIGHT_GENRES';

export const FETCH_TIME_GENRES_START = 'FETCH_TIME_GENRES_START';
export const FETCH_TIME_GENRES_SUCCESS = 'FETCH_TIME_GENRES_SUCCESS';
export const FETCH_TIME_GENRES_ERROR = 'FETCH_TIME_GENRES_ERROR';
