/*
 *
 * AnalysisPage constants
 *
 */

export const FETCH_ANALYSIS = 'FETCH_ANALYSIS';

export const FETCH_ANALYSIS_ACTIVEVIEWERS_START = 'FETCH_ANALYSIS_ACTIVEVIEWERS_START';
export const FETCH_ANALYSIS_ACTIVEVIEWERS_SUCCESS = 'FETCH_ANALYSIS_ACTIVEVIEWERS_SUCCESS';
export const FETCH_ANALYSIS_ACTIVEVIEWERS_ERROR = 'FETCH_ANALYSIS_ACTIVEVIEWERS_ERROR';

export const FETCH_ANALYSIS_CHURN_START = 'FETCH_ANALYSIS_CHURN_START';
export const FETCH_ANALYSIS_CHURN_SUCCESS = 'FETCH_ANALYSIS_CHURN_SUCCESS';
export const FETCH_ANALYSIS_CHURN_ERROR = 'FETCH_ANALYSIS_CHURN_ERROR';

export const FETCH_ANALYSIS_AVERAGEAMOUNT_START = 'FETCH_ANALYSIS_AVERAGEAMOUNT_START';
export const FETCH_ANALYSIS_AVERAGEAMOUNT_SUCCESS = 'FETCH_ANALYSIS_AVERAGEAMOUNT_SUCCESS';
export const FETCH_ANALYSIS_AVERAGEAMOUNT_ERROR = 'FETCH_ANALYSIS_AVERAGEAMOUNT_ERROR';

export const FETCH_ANALYSIS_AVERAGEVIEWTIME_START = 'FETCH_ANALYSIS_AVERAGEVIEWTIME_START';
export const FETCH_ANALYSIS_AVERAGEVIEWTIME_SUCCESS = 'FETCH_ANALYSIS_AVERAGEVIEWTIME_SUCCESS';
export const FETCH_ANALYSIS_AVERAGEVIEWTIME_ERROR = 'FETCH_ANALYSIS_AVERAGEVIEWTIME_ERROR';
