/*
 *
 * UserInsightInteractions constants
 *
 */

export const FETCH_USER_INSIGHT_INTERACTIONS = 'FETCH_USER_INSIGHT_INTERACTIONS';

export const FETCH_COMPLETENESS_START = 'FETCH_COMPLETENESS_START';
export const FETCH_COMPLETENESS_SUCCESS = 'FETCH_COMPLETENESS_SUCCESS';
export const FETCH_COMPLETENESS_ERROR = 'FETCH_COMPLETENESS_ERROR';

export const FETCH_AVERAGE_INTERACTIONS_START = 'FETCH_AVERAGE_INTERACTIONS_START';
export const FETCH_AVERAGE_INTERACTIONS_SUCCESS = 'FETCH_AVERAGE_INTERACTIONS_SUCCESS';
export const FETCH_AVERAGE_INTERACTIONS_ERROR = 'FETCH_AVERAGE_INTERACTIONS_ERROR';
