/*
 *
 * UserInsightPage constants
 *
 */
export const FETCH_USER_INSIGHT = 'FETCH_USER_INSIGHT';

export const FETCH_CONTENT_VIEWS = 'FETCH_CONTENT_VIEWS';
export const FETCH_CONTENT_VIEWS_SUCCESS = 'FETCH_CONTENT_VIEWS_SUCCESS';
export const FETCH_CONTENT_VIEWS_ERROR = 'FETCH_CONTENT_VIEWS_ERROR';

export const FETCH_TOP_MOVIES = 'FETCH_TOP_MOVIES';
export const FETCH_TOP_MOVIES_SUCCESS = 'FETCH_TOP_MOVIES_SUCCESS';
export const FETCH_TOP_MOVIES_ERROR = 'FETCH_TOP_MOVIES_ERROR';
