/*
 *
 * UserInsightPage constants
 *
 */

export const FETCH_CONTENT_VIEWS = 'FETCH_CONTENT_VIEWS';
export const FETCH_CONTENT_VIEWS_SUCCESS = 'FETCH_CONTENT_VIEWS_SUCCESS';
export const FETCH_CONTENT_VIEWS_ERROR = 'FETCH_CONTENT_VIEWS_ERROR';
