/*
 *
 * UserInsightMovies constants
 *
 */

export const FETCH_USER_INSIGHT_MOVIES = 'FETCH_USER_INSIGHT_MOVIES';

export const FETCH_CONTENT_VIEWS_START = 'FETCH_CONTENT_VIEWS_START';
export const FETCH_CONTENT_VIEWS_SUCCESS = 'FETCH_CONTENT_VIEWS_SUCCESS';
export const FETCH_CONTENT_VIEWS_ERROR = 'FETCH_CONTENT_VIEWS_ERROR';

export const FETCH_TOP_MOVIES_START = 'FETCH_TOP_MOVIES_START';
export const FETCH_TOP_MOVIES_SUCCESS = 'FETCH_TOP_MOVIES_SUCCESS';
export const FETCH_TOP_MOVIES_ERROR = 'FETCH_TOP_MOVIES_ERROR';
