/*
 *
 * UserInsightTransactions constants
 *
 */
export const FETCH_USER_INSIGHT_TRANSACTIONS = 'FETCH_USER_INSIGHT_TRANSACTIONS';

export const FETCH_TIME_TRANSACTIONS_START = 'FETCH_TIME_TRANSACTIONS_START';
export const FETCH_TIME_TRANSACTIONS_SUCCESS = 'FETCH_TIME_TRANSACTIONS_SUCCESS';
export const FETCH_TIME_TRANSACTIONS_ERROR = 'FETCH_TIME_TRANSACTIONS_ERROR';

export const FETCH_GENRE_TRANSACTIONS_START = 'FETCH_GENRE_TRANSACTIONS_START';
export const FETCH_GENRE_TRANSACTIONS_SUCCESS = 'FETCH_GENRE_TRANSACTIONS_SUCCESS';
export const FETCH_GENRE_TRANSACTIONS_ERROR = 'FETCH_GENRE_TRANSACTIONS_ERROR';
